<a href="https://colab.research.google.com/github/practiceprobs/problemsets/blob/main/python-numpy/advanced/peanut_butter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[![PracticeProbs](https://d33wubrfki0l68.cloudfront.net/b6800cc830e3fd5a3a4c3d9cfb1137e6a4c15c77/ec467/assets/images/transparent-1.png)](https://www.practiceprobs.com/)

# [Peanut Butter](https://www.practiceprobs.com/problemsets/python-numpy/advanced/peanut-butter/)

Given `peanut`, a 4x5 array of 0s, and `butter`, a 5-element 1-d array of indices, fill the rows of `peanut` with 1s starting from the column indices given by `butter`.

In [ ]:
import numpy as np

peanut = np.zeros(shape = (4, 5))
butter = np.array([3, 0, 4, 1])

print(peanut)
# [[0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0.]]

print(butter)
# [3 0 4 1]

---

In [ ]:
# Your brilliant solution here!

## [See our solution!](https://www.practiceprobs.com/problemsets/python-numpy/advanced/peanut-butter/solution/)